### PR TITLE
build: update package version

### PR DESCRIPTION
**Pull request by nichonien**

### CODE REVIEW

**Review by JGiter — CHANGES_REQUESTED** [review]
I think we would be better merge master into dev. We will need this in any case before merge dev in master. Besides master -> dev triggers versioning from 2.1.0

**Comment by nichonien** [comment]
> I think we would be better merge master into dev. We will need this in any case before merge dev in master. Besides master -> dev triggers versioning from 2.1.0

I am not sure, if this would work. IMO if you trigger this merge, it would still leave a difference in version the way it is now. Did you performed master -> dev merge before publish last time?

**Comment by JGiter** [comment]
Sorry for confusion
> Besides master -> dev triggers versioning from 2.1.0

is applies to semantic-release managed repos. But we still need to sync dev with master. I did it before

**Comment by nichonien** [comment]
> is applies to semantic-release managed repos. But we still need to sync dev with master. I did it before

I think this should not be the case if you already performed the master -> dev merge, the version should not be out of sync. Or would you like to give it a try again?

**Comment by nichonien** [comment]
@JGiter Looking at this PR - https://github.com/energywebfoundation/ew-credentials/pull/60, I think it would be good to investigate this a bit more. To me this seems to be persistent with every new publish maybe, What do you think?

**Comment by JGiter** [comment]
> To me this seems to be persistent with every new publish maybe

Yes, this needs to be fixed

**Review by JGiter — APPROVED** [review]

**Comment by nichonien** [comment]
Closing this as https://github.com/energywebfoundation/ew-credentials/pull/69 resolved the sync issue between develop and master.

**Pull request closed without merging**
