### PR TITLE
Sync with master

### PR DESCRIPTION
**Pull request by JGiter**

### CODE REVIEW

**Comment by jrhender** [comment]
Is this required after each push to `master` or only this once for some reason?

**Comment by JGiter** [comment]
This sync is exception. For some reason sync master -> develop wasn't happen on master publish

**Comment by jrhender** [comment]
You mean there was some error on the previous publish that caused the sync to fail?

**Comment by JGiter** [comment]
May be sync was canceled by `cancel-previous` action?

**Comment by jrhender** [comment]
Ah yes, I can see that the `sync to master` action was cancelled. https://github.com/energywebfoundation/ew-credentials/runs/7725413645?check_suite_focus=true do you know why this was?

**Review by jrhender — APPROVED** [review]
We can give it a try. If it ends up needs to be a repeated task, we can investigate then

**Comment by JGiter** [comment]
> Ah yes, I can see that the sync to master action was cancelled. https://github.com/energywebfoundation/ew-credentials/runs/7725413645?check_suite_focus=true do you know why this was?

I believe it was canceled by v2.0.0 action https://github.com/energywebfoundation/ew-credentials/actions/workflows/deploy.yml?query=branch%3Amaster

**Pull request merged**
